### ISSUE TITLE
Setup Kanbaan board

### ISSUE THREAD

**Issue by FrankMugagga** [Tshobohwa/recipe-app#15]
# Setup Kanbaan board

- [ ] In this milestone;
-  we created a Kanbaan board
- Assigned tasks to team members
- Created issues

- [ ] Link to Kanban project: https://github.com/users/Tshobohwa/projects/7

##NOTE: We are a group of two people only
@FrankMugagga 
@Tshobohwa

**Comment by bobb-Rob** [comment]
## STATUS: CHANGES REQUIRED ♻️
Hi @FrankMugagga and @Tshobohwa, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ Very descriptive Kanban cards

## Required Changes ♻️

- [ ] I did not find any card that speaks to the requirement below :
   - Make sure there are no N+1 queries happening.

- [ ] The card below lacks a point estimation of the level of effort. please include that
![image](https://github.com/Tshobohwa/recipe-app/assets/84156714/06d1d8ae-374e-48a0-8e22-849dee965c58)

Please fix this

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by ichala** [comment]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
